
version: '2'

services:

  orderer.gbtcodeminers.com:
    container_name: orderer.gbtcodeminers.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../bin/crypto-config/ordererOrganizations/gbtcodeminers.com/orderers/orderer.gbtcodeminers.com/msp:/var/hyperledger/orderer/msp
    - ../bin/crypto-config/ordererOrganizations/gbtcodeminers.com/orderers/orderer.gbtcodeminers.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 8050:7050

  peer0.org1.gbtcodeminers.com:
    container_name: peer0.org1.gbtcodeminers.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.gbtcodeminers.com
      - CORE_PEER_ADDRESS=peer0.org1.gbtcodeminers.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.gbtcodeminers.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.gbtcodeminers.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../bin/crypto-config/peerOrganizations/org1.gbtcodeminers.com/peers/peer0.org1.gbtcodeminers.com/msp:/etc/hyperledger/fabric/msp
        - ../bin/crypto-config/peerOrganizations/org1.gbtcodeminers.com/peers/peer0.org1.gbtcodeminers.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 8051:7051
      - 8053:7053

  peer0.org2.gbtcodeminers.com:
    container_name: peer0.org2.gbtcodeminers.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org2.gbtcodeminers.com
      - CORE_PEER_ADDRESS=peer0.org2.gbtcodeminers.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.gbtcodeminers.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.gbtcodeminers.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../bin/crypto-config/peerOrganizations/org2.gbtcodeminers.com/peers/peer0.org2.gbtcodeminers.com/msp:/etc/hyperledger/fabric/msp
        - ../bin/crypto-config/peerOrganizations/org2.gbtcodeminers.com/peers/peer0.org2.gbtcodeminers.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 9051:7051
      - 9053:7053

  peer0.org3.gbtcodeminers.com:
    container_name: peer0.org3.gbtcodeminers.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org3.gbtcodeminers.com
      - CORE_PEER_ADDRESS=peer0.org3.gbtcodeminers.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.gbtcodeminers.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org3.gbtcodeminers.com:7051
      - CORE_PEER_LOCALMSPID=Org3MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../bin/crypto-config/peerOrganizations/org3.gbtcodeminers.com/peers/peer0.org3.gbtcodeminers.com/msp:/etc/hyperledger/fabric/msp
        - ../bin/crypto-config/peerOrganizations/org3.gbtcodeminers.com/peers/peer0.org3.gbtcodeminers.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 6051:7051
      - 6053:7053
